{{- with .Values }}
{{- if .httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "grw.fullname" $ }}
  namespace: {{ include "grw.namespace" $ }}
  labels:
    {{- include "grw.labels" $ | nindent 4 }}
  {{- with .commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .httproute.parentRefs | nindent 4 }}

  {{- with .hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  rules:
    - matches:
        {{- toYaml .httproute.matches | nindent 8 }}
      backendRefs:
        - name: {{ include "grw.fullname" $ }}
          port: 8000
{{- end }}
{{- end }}
