{{- with .Values }}
{{- if not .config.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grw.fullname" $ }}
  namespace: {{ include "grw.namespace" $ }}
  labels:
    {{- include "grw.labels" $ | nindent 4 }}
  {{- with .commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  REDMINE_KEY: "{{ .config.REDMINE_KEY }}"
{{- end }}
{{- end }}
