{{- with .Values.serviceAccount }}
{{- if .create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grw.serviceAccountName" $ }}
  namespace: {{ include "grw.namespace" $ }}
  labels:
    {{- include "grw.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
